dist: trusty
sudo: required

language: java

branches:
  only:
    - develop
  # - Your branch name

deploy:
  provider: heroku
  app:
    develop: polyhedron-backend

  api_key:
    develop:
      secure: ihDLkfrCm6YSovH1LWjDH2dm9gEoZS9WDIpCYF+rlFYqQ2aZdu9i9CILIxoGv6+GIuF9kJDRfmhRSMDOsu0MQ4VfNeYAE/Li4KBDJDPsR3mAtBM2OZ8UiokJZR5WsqUFa11De1JQKzIOHMuquOVsv+l/rMk83vpdVvz1w6Tp2vdB/WFY9NmlPpycUackAPVZbE3EUuZMKqa4dIgqGzu7whXTRBCv2QV647a9ZOLPSH9Q65IEMY/xdywka4VSzXugFu2IjySqvAdzux8J6ktuoULrT7/R1MbTdJCitQQkqXfASUJxvGfTcvhxXe0Gi4846AEIUS0hbrx7v6CU3tfD7foifR6B963ulk9TFzUOn5dbnHlaVgWzDmu67fdmap2bmQK6OYed/NnYvq5GcPh7ONR+jEbfsniSV4Mrqyvcuf/75qiaMu7vyjLErqfz9mt6XSv/wyGJfmQ2GPsRyIThiyWtgyWl+i4przDlv18kYDwe63HM7pg2zVleatT+dVGJdfknvslX+d/9Eoi5JPKDXmj1xSh31WABXBye8O5wbEFstWlTuFWepGc1hJhHi1ICRSn96tPXiEOWfIO3EooSeqqjsNAyJfFVOrzDzyC1R+w+XqiNC/goVJ1t+YUD3NSXwiyQCsUMnTqsspH1UEkqQGI6QeM+fuYw52uAJa+swBI=
