dist: trusty
sudo: required

language: java

branches:
  only:
    - develop
  # - Your branch name

deploy:
  provider: heroku
  app:
    develop: polyhedron-backend

  api_key:
    develop:
      secure: PeCBJ82llzSQBOC8cQ+x3do8l/KaIN7nFNTSkUuArcoFx1CxFPiCUFZeGla//Y5bA3OqGijQPbMo0tbpeEncPCCSlPND4dDXs4mE1txEWyRidu3hCzv5Y1/XAQJOk+jW4B9SnvKlmGqR2woJRJwMHu+5mVZyqJVc1lALmMbnBsHbD08VktLYRmdcTHTCsJhzvwrpBqWbFgL+A5HUcN6lr48dmdobbCciakw/vUWdjtYG/tIvaG5cMB9eb0nvfhVasE9CvWozRbIghrYi6zjpdnsmfCd/GCVtY18QuG3C5J+qpb7ADgbLFa4EXy0O8gPf3gHqqfkgcThQ0Hf2l27rGOJzC8MEfKhmRfA6kRNTWeVzGPKfZvNL941M6SpBjxMHVn/m1ExiieT0dmvy1ZkXsRComY2JaLzxbYTVkqtERzZRrbTnm5McdUHR1eBQ/sBmG/w6auvvbmFJCJnVb7a8m+cbRWBiqozIazYBgfBGOYPr5pSMQ2apYhikekJ922lKMTT7xB+1AG8lbGDubPRfm4+c928/i3YJ1fQdAv5Wj2neMRomQUJfIUsJ2lOVLbsllpZAxDtVTXtTbD6aIpg8fvmCb0NEUtxXRMDk1UX2cHTbA1FnvID41hg1yJQicbgFWYt36dbqBsA0hLNpIaSjJz5aQ2Dc3KND/or7vcOCcEA=
