dist: trusty
sudo: required

language: java

branches:
  only:
    - develop
  # - Your branch name

deploy:
  provider: heroku
  app:
    develop: polyhedron-backend

  api_key:
    develop:
      secure: R1luexUvlcK/J/Du46aeTN+grQiVOxS99YFN24pDduJEYOfB2AezwRbbilHvXMZlku153X6Umg99fuwsFivEA9MEFtGrElRdlPCqmHqh9qh0+2/bGq8HrURVI6IouTokHVZObj0hQqNc2+jE5VWPUMbuKlzt/Cbb318uWOtDVjxVT6bYVCh5/e0ikcldK0Pc/r+kLnb9HW9KWtoBMXsQJwLI2NZiPmnWzMkVOfgn2xlxP38+EKskbJfxNuSLFR7/08ob3E/lNAZX6X+v9++WZx02HfzUXmRDwqxRBXISj4ivowohE7SWtsPHi6SPM3BP/THLXmZwDxqTyw4pKp8l1lYs3Mv83glGYwC9uaDgCOqUF8KbwNqJlCRw4KmSIuWcnzrKFPFHup7rvDkbm0xD8wMwrHXYPoC6GBwbvvlJZEyMA++oDoUJWC/OgxLY8xcGn3+imX5EeWdKYbSPOHAqrnyddO6hJgW1299n9xSiJQSnWm4b5QCjuzsagUxAOzB7wuQR4ggPxzL1WYul10UvXJf84kttblaY+sMpj4lRx0IDi2EN50pQSzH2F9AuijDhtInvPBrGzRoEjC1SCB40NGaoxGTsiJTMJD5+AtkfbtHiELghpsak4jNgdUq4iAVV+vFDzd8ImF7PeJ2INZW2rEMoNhp1EQ0GBwfGN+MrFFs=
