dist: trusty
sudo: required

language: java
jdk:
- oraclejdk7
- openjdk6

branches:
  only:
    - develop
  # - Your branch name

deploy:
  provider: heroku
  app:
    develop: polyhedron-backend

  api_key:
    develop:
      secure: AUyb87Ssi/qYRegWV5ALIzETZLzZWMyorqdUs7xMPQMEcJEGHFEvN2jO2gQo4KpZ9EP0y35U2z4Yqw8TiGF86ftUuz6+M1WhyDM/8xWhqy3YPEN0GNWnWhyONGkK5ByC+EBJz5VucFV5U6DfsHO9LvRsyUtHThrJyubTyNWPChz6nSWHWC8iMoaz1U+LeIzcMIOPtRCN2T5ZnfU5N5xe+8wWAWRZqWrVRGSqO85U0ntHrr6wqWVZo8+oIH8Abvs7FN0ByAWYZmB1fHE5c6tra2lr7/m0u6VVfw3OO8YozDc10ytiz8qNGDGOxChhFNtob0ZXhGUIp/9KJaYnOkA1wB1RRxCbZS25+V3VG2sjvWQxBtlSEmb+vmugBq9+IvtQsSH0voiK62Q66naMEd5PHoGubyg/td7eccT5VgSBrEpEWEvPwAqqUsExCgDWmXkqd8h8CO3j1BdGgBB3JzH7/lfTza3h7ueaFzPUqCZJswEJdtpJPcGZv19duW5F6+obsBnRs2Vc/EtMG6zd/+yRmRvcuuXglSak5rKdKL0IqC2PLT8390m+QA0YfyGiH8yGDi5Iv9cIKyd0uQS8wOVeCmfgYbKMIB0Fn5M9q70dVbPORgMoxtkWmq3ode0ct6DWRiGcOKNucALlh9OgkUsr7gej4IRTR00EOOBKSuUHFko=
