dist: trusty
sudo: required

language: java

branches:
  only:
    - develop
  # - Your branch name

deploy:
  provider: heroku
  app:
    develop: polyhedron-backend

  api_key:
    develop:
      secure: hcKigEUeFOIrkp64TFvLZO03Eiu0klq+x7H4ERRNlaNKT3qiCrNzSoSPYWalPdLW9j4BhmCaQUKZ1KiZKY4dhlVumn+0r5V1qFiej2sjdxU2gEWf5QPkm8/KP4C6wl7pHHv1NyKe6Nzq7rN8pOGaOg0Ot4MXmoz2kt+ubapSZMJ/APnbXU2AFTClHl0O1VhqT3ahyVkoao7CkcjcXQwwUWmNU0GqSXYmSCsG6OLkYRkksYR1nhu/aoINC/0qllYy58wIXfx7w2KZIhWSfHDnlNE1HErRpWVpiMz44RqOs3e8TeTKfWygD/PNKBkgU45ecHTD5MaUVXgtNEEMdGM5BGjdhJfXsxZcP0+WC6+X9+iLjgn+DZNccM5cWkFliakMQTseOEnIUpBJpxo2qhZ3exsZOsOJXcbuHuQqCbT/kSUInIWLeAww2iXKob1b8K2+NU2hu5sdBxIRD95Gf5gdEcC+zbdi2lRNQKBYP0R+QkFqQpsERdUvq8uhj4uK2Eh4E2wbYIYHNrsfq3UmYb4aH3IW2/C2lfQEgrLA/bj3527FYqB7A+MiumAQdJFbZ+fjzK1FN5a98KL1yTf63+DhIjrBEh8a0FdO7mRJlUDFkx38TiP2HX8Y3AMEY14klKtFi8kTjGvA1ms5hY1OItgjQSPrYzYLHEhqXqYh/c3Zkw8=
